In [6]:
import pandas as pd
energy = pd.read_csv('raw_data/Energy_Usage_2010_20260421.csv')
benchmark = pd.read_csv('raw_data/Chicago_Energy_Benchmarking_-_Covered_Buildings_20260421.csv')
complaints = pd.read_csv('raw_data/CDPH_Environmental_Complaints_20260421.csv')

energy.head(), benchmark.head(), complaints.head()

C:\Users\avapu\AppData\Local\Temp\ipykernel_26420\4095855623.py:2: DtypeWarning: Columns (18,67) have mixed types. Specify dtype option on import or set low_memory=False.
  energy = pd.read_csv('raw_data/Energy_Usage_2010_20260421.csv')

(  COMMUNITY AREA NAME  CENSUS BLOCK BUILDING TYPE BUILDING_SUBTYPE  \
 0      Archer Heights  1.703157e+14   Residential        Multi < 7
 1             Ashburn  1.703170e+14   Residential         Multi 7+
 2      Auburn Gresham  1.703171e+14    Commercial        Multi < 7
 3              Austin  1.703125e+14    Commercial        Multi < 7
 4              Austin  1.703125e+14    Commercial        Multi < 7

   KWH JANUARY 2010 KWH FEBRUARY 2010 KWH MARCH 2010 KWH APRIL 2010  \
 0              NaN               NaN            NaN            NaN
 1            7,334             7,741          4,214          4,284
 2              NaN               NaN            NaN            NaN
 3              NaN               NaN            NaN            NaN
 4              NaN               NaN            NaN            NaN

   KWH MAY 2010 KWH JUNE 2010  ... TOTAL POPULATION TOTAL UNITS  \
 0          NaN           NaN  ...               89          24
 1        2,518         4,273  ...              112          67
 2          NaN           NaN  ...              102          48
 3          NaN           NaN  ...              121          56
 4          NaN           NaN  ...               62          23

   AVERAGE STORIES AVERAGE BUILDING AGE AVERAGE HOUSESIZE OCCUPIED UNITS  \
 0             2.0                71.33              3.87             23
 1             2.0                41.00              1.81             62
 2             3.0                86.00                 3             34
 3             2.0                84.00              2.95             41
 4             2.0                85.00              3.26             19

   OCCUPIED UNITS PERCENTAGE RENTER-OCCUPIED HOUSING UNITS  \
 0                    0.9582                             9
 1                    0.9254                            50
 2                    0.7082                            23
 3                    0.7321                            32
 4                    0.8261                            11

   RENTER-OCCUPIED HOUSING PERCENTAGE OCCUPIED HOUSING UNITS
 0                             0.3910                     23
 1                             0.8059                     62
 2                             0.6759                     34
 3                             0.7800                     41
 4                             0.5790                     19

 [5 rows x 73 columns],
    Building ID                  Address    Zip Cohort - Sector  \
 0       251626        4929 N Sawyer Ave  60625       Municipal
 1       250014          2949 E 131st St  60633       Municipal
 2       105044  2018 2040 W Farwell Ave  60645     Residential
 3       254316      2544 W Montrose Ave  60618      Commercial
 4       251445       4619 S Wolcott Ave  60609       Municipal

     Cohort - Size  Verification Year Community Area Name  \
 0  > 50,000 Sq Ft             2025.0         Albany Park
 1  > 50,000 Sq Ft             2025.0           Hegewisch
 2  > 50,000 Sq Ft             2025.0          West Ridge
 3  > 50,000 Sq Ft             2027.0      Lincoln Square
 4  > 50,000 Sq Ft             2025.0            New City

    Community Area Number  Ward  Latitude  Longitude               Location
 0                     14    33  41.97110  -87.70939   (41.9711, -87.70939)
 1                     55    10  41.65732  -87.55272  (41.65732, -87.55272)
 2                      2    50  42.00880  -87.69503   (42.0088, -87.69503)
 3                      4    47  41.94662  -87.70269  (41.94662, -87.70269)
 4                     61    15  41.80974  -87.67190   (41.80974, -87.6719)  ,
   COMPLAINT ID            COMPLAINT TYPE                ADDRESS  \
 0    601749668  Air Pollution Work Order  10430 S GREEN BAY AVE
 1    601601110  Air Pollution Work Order         3811 W LAKE ST
 2         2980           Noise Complaint     980 N MICHIGAN AVE
 3    600782232  Air Pollution Work Order    9542 S WOODLAWN AVE
 4    601749670  Air Pollution Work Order    11300 S LANGLEY AVE

    STREET NUMBER FROM  STREET NUMBER TO DIRECTION STREET NAME STREET TYPE  \
 0               10430               NaN         S   GREEN BAY         AVE
 1                3811               NaN         W        LAKE          ST
 2                 980               NaN         N    MICHIGAN         AVE
 3                9542               NaN         S    WOODLAWN         AVE
 4               11300               NaN         S     LANGLEY         AVE

   INSPECTOR COMPLAINT DATE                                   COMPLAINT DETAIL  \
 0     13776     09/28/2025                                                NaN
 1    417337     09/06/2024                                                NaN
 2     10937            NaN                                                NaN
 3     13776            NaN                                    SR# 20-03426905
 4     13776     09/26/2025  &nbsp;Caller says every night, only at night f...

               DATA SOURCE                   RESOLUTION RESOLVED DATE  \
 0  DEPT. OF PUBLIC HEALTH  Alleged violation not found    09/29/2025
 1  DEPT. OF PUBLIC HEALTH              Complaint Valid    09/09/2024
 2  DEPT. OF PUBLIC HEALTH            Complaint Invalid    02/21/2012
 3  DEPT. OF PUBLIC HEALTH  Alleged violation not found    01/31/2020
 4  DEPT. OF PUBLIC HEALTH                     Resolved    09/29/2025

     LATITUDE  LONGITUDE                                  LOCATION
 0  41.705463 -87.541485   POINT (-87.54148545281 41.705463194561)
 1  41.885123 -87.721403    POINT (-87.721402854172 41.8851233932)
 2  41.900802 -87.624272   POINT (-87.62427246793 41.900801649452)
 3  41.720899 -87.594899  POINT (-87.594898536828 41.720899246873)
 4  41.689106 -87.606069  POINT (-87.606069115875 41.689105712151)  )

Clean Energy Usage

In [7]:

energy.columns = energy.columns.str.strip().str.replace(' ', '_')

# convert numeric columns
numeric_cols = energy.select_dtypes(include='object').columns
for col in numeric_cols:
    energy[col] = pd.to_numeric(energy[col], errors='ignore')

energy = energy.drop_duplicates()
energy = energy.fillna(0)

energy.head()

C:\Users\avapu\AppData\Local\Temp\ipykernel_26420\3726717236.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  energy[col] = pd.to_numeric(energy[col], errors='ignore')

,COMMUNITY_AREA_NAME,CENSUS_BLOCK,BUILDING_TYPE,BUILDING_SUBTYPE,KWH_JANUARY_2010,KWH_FEBRUARY_2010,KWH_MARCH_2010,KWH_APRIL_2010,KWH_MAY_2010,KWH_JUNE_2010,...,TOTAL_POPULATION,TOTAL_UNITS,AVERAGE_STORIES,AVERAGE_BUILDING_AGE,AVERAGE_HOUSESIZE,OCCUPIED_UNITS,OCCUPIED_UNITS_PERCENTAGE,RENTER-OCCUPIED_HOUSING_UNITS,RENTER-OCCUPIED_HOUSING_PERCENTAGE,OCCUPIED_HOUSING_UNITS
0,Archer Heights,1.703157e+14,Residential,Multi < 7,0,0,0,0,0,0,...,89,24,2.0,71.33,3.87,23,0.9582,9,0.3910,23
1,Ashburn,1.703170e+14,Residential,Multi 7+,"7,334","7,741","4,214","4,284","2,518","4,273",...,112,67,2.0,41.00,1.81,62,0.9254,50,0.8059,62
2,Auburn Gresham,1.703171e+14,Commercial,Multi < 7,0,0,0,0,0,0,...,102,48,3.0,86.00,3,34,0.7082,23,0.6759,34
3,Austin,1.703125e+14,Commercial,Multi < 7,0,0,0,0,0,0,...,121,56,2.0,84.00,2.95,41,0.7321,32,0.7800,41
4,Austin,1.703125e+14,Commercial,Multi < 7,0,0,0,0,0,0,...,62,23,2.0,85.00,3.26,19,0.8261,11,0.5790,19

Clean Benchmark Data

In [8]:

benchmark.columns = benchmark.columns.str.strip().str.replace(' ', '_')
benchmark = benchmark.drop_duplicates()
benchmark = benchmark.fillna(method='ffill')

benchmark.head()

C:\Users\avapu\AppData\Local\Temp\ipykernel_26420\81450329.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  benchmark = benchmark.fillna(method='ffill')

,Building_ID,Address,Zip,Cohort_-_Sector,Cohort_-_Size,Verification_Year,Community_Area_Name,Community_Area_Number,Ward,Latitude,Longitude,Location
0,251626,4929 N Sawyer Ave,60625,Municipal,"> 50,000 Sq Ft",2025.0,Albany Park,14,33,41.97110,-87.70939,"(41.9711, -87.70939)"
1,250014,2949 E 131st St,60633,Municipal,"> 50,000 Sq Ft",2025.0,Hegewisch,55,10,41.65732,-87.55272,"(41.65732, -87.55272)"
2,105044,2018 2040 W Farwell Ave,60645,Residential,"> 50,000 Sq Ft",2025.0,West Ridge,2,50,42.00880,-87.69503,"(42.0088, -87.69503)"
3,254316,2544 W Montrose Ave,60618,Commercial,"> 50,000 Sq Ft",2027.0,Lincoln Square,4,47,41.94662,-87.70269,"(41.94662, -87.70269)"
4,251445,4619 S Wolcott Ave,60609,Municipal,"> 50,000 Sq Ft",2025.0,New City,61,15,41.80974,-87.67190,"(41.80974, -87.6719)"

Clean Complaints Data

In [9]:

complaints.columns = complaints.columns.str.strip().str.replace(' ', '_')
complaints['COMPLAINT_DATE'] = pd.to_datetime(complaints['COMPLAINT_DATE'], errors='coerce')
complaints = complaints.drop_duplicates()
complaints = complaints.fillna('Unknown')

complaints.head()

,COMPLAINT_ID,COMPLAINT_TYPE,ADDRESS,STREET_NUMBER_FROM,STREET_NUMBER_TO,DIRECTION,STREET_NAME,STREET_TYPE,INSPECTOR,COMPLAINT_DATE,COMPLAINT_DETAIL,DATA_SOURCE,RESOLUTION,RESOLVED_DATE,LATITUDE,LONGITUDE,LOCATION
0,601749668,Air Pollution Work Order,10430 S GREEN BAY AVE,10430,Unknown,S,GREEN BAY,AVE,13776,2025-09-28 00:00:00,Unknown,DEPT. OF PUBLIC HEALTH,Alleged violation not found,09/29/2025,41.705463,-87.541485,POINT (-87.54148545281 41.705463194561)
1,601601110,Air Pollution Work Order,3811 W LAKE ST,3811,Unknown,W,LAKE,ST,417337,2024-09-06 00:00:00,Unknown,DEPT. OF PUBLIC HEALTH,Complaint Valid,09/09/2024,41.885123,-87.721403,POINT (-87.721402854172 41.8851233932)
2,2980,Noise Complaint,980 N MICHIGAN AVE,980,Unknown,N,MICHIGAN,AVE,10937,Unknown,Unknown,DEPT. OF PUBLIC HEALTH,Complaint Invalid,02/21/2012,41.900802,-87.624272,POINT (-87.62427246793 41.900801649452)
3,600782232,Air Pollution Work Order,9542 S WOODLAWN AVE,9542,Unknown,S,WOODLAWN,AVE,13776,Unknown,SR# 20-03426905,DEPT. OF PUBLIC HEALTH,Alleged violation not found,01/31/2020,41.720899,-87.594899,POINT (-87.594898536828 41.720899246873)
4,601749670,Air Pollution Work Order,11300 S LANGLEY AVE,11300,Unknown,S,LANGLEY,AVE,13776,2025-09-26 00:00:00,"&nbsp;Caller says every night, only at night f...",DEPT. OF PUBLIC HEALTH,Resolved,09/29/2025,41.689106,-87.606069,POINT (-87.606069115875 41.689105712151)

Save Cleaned Data

In [11]:
energy.to_csv('clean_data/clean_energy.csv', index=False)
benchmark.to_csv('clean_data/clean_benchmark.csv', index=False)
complaints.to_csv('clean_data/clean_complaints.csv', index=False)